export enum Status {
  Continue = 100,
  SwitchingProtocols = 101,
  Processing = 102,
  EarlyHints = 103,
  OK = 200,
  Created = 201,
  Accepted = 202,
  NonAuthoritativeInformation = 203,
  NoContent = 204,
  ResetContent = 205,
  PartialContent = 206,
  MultiStatus = 207,
  AlreadyReported = 208,
  IMUsed = 226,
  MultipleChoices = 300,
  MovedPermanently = 301,
  Found = 302,
  SeeOther = 303,
  NotModified = 304,
  UseProxy = 305,
  SwitchProxy = 306,
  TemporaryRedirect = 307,
  PermanentRedirect = 308,
  BadRequest = 400,
  Unauthorized = 401,
  PaymentRequired = 402,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  NotAcceptable = 406,
  ProxyAuthenticationRequired = 407,
  RequestTimeout = 408,
  Conflict = 409,
  Gone = 410,
  LengthRequired = 411,
  PreconditionFailed = 412,
  PayloadTooLarge = 413,
  URITooLong = 414,
  UnsupportedMediaType = 415,
  RangeNotSatisfiable = 416,
  ExpectationFailed = 417,
  Teapot = 418,
  MisdirectedRequest = 421,
  UnprocessableEntity = 422,
  Locked = 423,
  FailedDependency = 424,
  TooEarly = 425,
  UpgradeRequired = 426,
  PreconditionRequired = 428,
  TooManyRequests = 429,
  RequestHeaderFieldsTooLarge = 431,
  UnavailableForLegalReasons = 451,
  InternalServerError = 500,
  NotImplemented = 501,
  BadGateway = 502,
  ServiceUnavailable = 503,
  GatewayTimeout = 504,
  HTTPVersionNotSupported = 505,
  VariantAlsoNegotiates = 506,
  InsufficientStorage = 507,
  LoopDetected = 508,
  NotExtended = 510,
  NetworkAuthenticationRequired = 511
}

export enum ContentType {
  APPLICATION = "application/*",
  APPLICATION_RTF = "application/rtf",
  APPLICATION_ZIP = "application/zip",
  APPLICATION_X_RAR = "application/x-rar-compressed",
  APPLICATION_X_TAR = "application/x-tar",
  APPLICATION_X_TZ_COMPRESSED = "application/x-7z-compressed",
  APPLICATION_X_WWW_FORM_URLENCODED = "application/x-www-form-urlencoded",
  APPLICATION_PDF = "application/pdf",
  APPLICATION_JSON = "application/json",
  APPLICATION_JAVASCRIPT = "application/javascript",
  APPLICATION_ECMASCRIPT = "application/ecmascript",
  APPLICATION_XML = "application/xml",
  APPLICATION_OCTET_STREAM = "application/octet-stream",
  APPLICATION_VND_API_JSON = "application/vnd.api+json",
  TEXT_PLAIN = "text/plain",
  TEXT_HTML = "text/html",
  TEXT_CSS = "text/css",
  TEXT_CSV = "text/csv",
  IMAGE_WEBP = "image/webp",
  IMAGE_JPEG = "image/jpeg",
  IMAGE_PNG = "image/png",
  IMAGE_GIF = "image/gif",
  IMAGE_TIFF = "image/tiff",
  IMAGE_SVG_XML = "image/svg+xml",
  AUDIO_MPEG = "audio/mpeg",
  AUDIO_OGG = "audio/ogg",
  AUDIO = "audio/*",
  VIDEO_WEBM = "video/webm",
  VIDEO_MP4 = "video/mp4",
  FONT_TTF = "font/ttf",
  FONT_WOFF = "font/woff",
  FONT_WOFF2 = "font/woff2",
  MULTIPART_FORM_DATA = "multipart/form-data"
}

export interface CookieOptions {
  readonly expires?: Date;
  readonly domain?: string;
  readonly httpOnly?: boolean;
  readonly maxAge?: number;
  readonly path?: string;
  readonly sameSite?: boolean | "strict" | "lax";
  readonly secure?: boolean;
  readonly signed?: boolean;
}

export type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS";
